- name: Perform safe restart steps
  when: restart_platform_safe
  block:
    - name: Deactivate job workers
      itential.platform.deactivate_job_worker:

    - name: Deactivate task workers
      itential.platform.deactivate_task_worker:

    - name: Wait until only manual tasks remain
      itential.platform.get_tasks:
        status: running
      register: active_tasks
      until: (active_tasks.json.data | rejectattr('type', 'equalto', 'manual') | list | length) == 0
      retries: 30
      delay: 10

- name: Restart platform service
  ansible.builtin.systemd:
    name: itential-platform
    state: restarted
