all:
  vars:
    ansible_user: <some-user-name>
    ansible_ssh_private_key_file: <path-to-key>
  children:
    redis:
      hosts:

    rabbitmq:
      hosts:

    mongodb:
      hosts:
      vars:
        mongo_username: admin
        mongo_password: admin
        mongo_auth_db: admin       

    mongodb_arbiter:
      hosts:

    platform:
      hosts:
      vars:
        iap_protocol: http
        iap_port: 3000
        iap_username: admin@pronghorn
        iap_password: admin

    gateway:
      hosts:
      vars: