# Copyright (c) 2024, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Example usage:
# ansible-playbook -i hosts change_redis_password.yml"

# - name: Change redis password
#   hosts: redis
#   gather_facts: false
#   tasks:
#     - name: Change the redis password in redis conf file
#       ansible.builtin.lineinfile:
#         path: /etc/redis/redis.conf
#         regexp: ^(user {{ user }}\s.*>).*$
#         line: \1{{ new_password }}
#         backrefs: true
    
#     - name: Check if sentinel file exists
#       ansible.builtin.stat:
#         path: /etc/redis/sentinel.conf
#       register: sentinel_exists
    
#     - name: Change the password in sentinel file
#       ansible.builtin.lineinfile:
#         path: etc/redis/redis.conf
#         regexp: ^(user {{ user }}.*>).*(\s.*)$
#         line: '\1{{ new_password }}\2'
#         backrefs: true
#       when: sentinel_exists.stat.exists

- name: Update password references in IAP
  hosts: platform
  gather_facts: false
  connection: local
  tasks:
    - name: Login to IAP and get token
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/login"
        method: POST
        body: '{"username": "{{ iap_username }}", "password": "{{ iap_password }}"}'
        body_format: json
        headers:
          Content-Type: "application/json"
        status_code: 200
        return_content: yes
      register: token
    
    - name: Extract token from login response
      set_fact:
        auth_token: "?token={{ token.content }}"
    
    - name: Get list of all profiles
      ansible.builtin.uri:
          url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/profiles{{ auth_token }}"
          method: GET
          status_code: 200
          return_content: yes
      register: profiles
    
    - name: Display profiles
      ansible.builtin.debug:
        msg: 
        - "{{ profiles.json }}"


    # - name: Update redis password for itential user in active profile
    #   ansible.builtin.uri:
    #     url: "localhost:{{ iap_port }}/profiles/{{ id }}{{ auth_token }}"
    #     method: PUT
    #     body: '{"properties": {"redisProps": {"password": "{{ new_password }}"}}}'
    #     body_format: json
    #     headers:
    #       Content-Type: "application/json"
    #     status_code: 200
    #     return_content: yes
    #   register: update_response
    #   when: user == "itential"
    
    # - name: Update redis password for sentinel user in active profile
    #   community.mongodb.mongodb_shell:
    #     login_user: itential_username
    #     login_password: itential_password
    #     db: "itential"
    #     login_database: "itential"
    #     eval: "db.iap_profiles.updateOne({'id': '{{ id }}'}, {'$set': {'redisProps.sentinelPassword': '{{ new_password }}'}})"
    #     when: user == "sentineluser"



