# Example usage:
# ansible-playbook -i hosts metrics.yml 
- name: IAP Metrics
  hosts: platform
  gather_facts: false
  vars:
    ansible_connection: local
    
  tasks:

    - name: Login to IAP and get token
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/login"
        method: POST
        body: '{"username": "{{ iap_username }}", "password": "{{ iap_password }}"}'
        body_format: json
        headers:
          Content-Type: "application/json"
        status_code: 200
        return_content: yes
      register: token

    - name: Extract token from login response
      set_fact:
        auth_token: "?token={{ token.content }}"


    - name: Get workflow count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/automation-studio/workflows{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: workflows

    - name: Get template count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/automation-studio/templates{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: templates

    - name: Get transformation count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/transformations{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: transformations

    - name: Get MOP templates count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/mop/listTemplates{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: mop

    - name: Get analytic templates count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/mop/listAnalyticTemplates{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: analytictemplates

    - name: Get jobs count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/operations-manager/jobs{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: jobs

    - name: Get automations count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/operations-manager/automations{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: automations
    
    - name: Get form count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/formbuilder/listForms{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: forms

    - name: Get json form count
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/json-forms/forms{{ auth_token }}"
        method: GET
        status_code: 200
        return_content: yes
      register: jsonforms

    - name: Display metrics
      ansible.builtin.debug:
        msg: 
        - "Metrics of {{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}"
        - "====================================================="
        - "Workflow count: {{ workflows.json.count }} " 
        - "Template count: {{ templates.json.count }} " 
        - "MOP template count: {{ mop.json | length }} "
        - "Analytic template count: {{ analytictemplates.json | length }} " 
        - "JST count: {{ transformations.json.total }} " 
        - "JSON form count: {{ jsonforms.json | length }} " 
        - "Form count: {{ forms.json | length }} " 
        - "Job count: {{ jobs.json.metadata.total }} " 
        - "Automation count: {{ automations.json.metadata.total }} " 
