# Example usage:
# ansible-playbook -i hosts mongo_dump.yml -e "db=itential collection=workflows"
- name: Mongodump
  hosts: mongodb
  gather_facts: false

  tasks:

    - name: Dump all collections
      ansible.builtin.command: mongodump -u {{mongo_username}} -d {{db}} -p {{mongo_password}} --authenticationDatabase={{mongo_auth_db}}
      when: collection is undefined
    
    - name: Dump single collection
      ansible.builtin.command: mongodump -u {{mongo_username}} -d {{db}} -p {{mongo_password}} --authenticationDatabase={{mongo_auth_db}} -c {{collection}}
      when: collection is defined