# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Example usage:
# ansible-playbook -i hosts rbac_settings.yml

- name: RBAC Settings
  hosts: platform
  gather_facts: false
  tasks:
    - name: Retrieve authorization accounts
      itential.platform.generic_request:
        method: GET
        endpoint: "/authorization/accounts"
      register: auth_accounts

    - name: Retrieve available roles
      itential.platform.generic_request:
        method: GET
        endpoint: "/authorization/roles"
      register: roles_response

    - name: Process RBAC Data
      itential.toolkit.iap_rbac_processing:
        auth_accounts: "{{ auth_accounts.json.results }}"
        roles_response: "{{ roles_response.json.results }}"
        users: "{{ users }}"
      register: rbac_results

    - name: Display the RBAC Settings for users
      ansible.builtin.debug:
        msg: "{{ rbac_results.formatted_message.split('\n') }}"
