# Copyright (c) 2023, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Example usage:
# ansible-playbook -i hosts create_adapter.yml

- name: Create Adapter
  hosts: platform
  gather_facts: false
  connection: local
  vars_prompt:
    - name: adapter_properties_file
      prompt: "Provide the file name of the adapter properties"
      private: false

    - name: iap_username
      prompt: "IAP username"
      private: false

    - name: iap_password
      prompt: "IAP Password"

  vars:
    adapter_properties: "{{ lookup('file', adapter_properties_file) | from_json }}"
  
  tasks:
    - name: Login to IAP and get token
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/login"
        method: POST
        body: '{"username": "{{ iap_username }}", "password": "{{ iap_password }}"}'
        body_format: json
        headers:
          Content-Type: "application/json"
        status_code: 200
        return_content: yes
      register: token

    - name: Extract token from login response
      set_fact:
        auth_token: "?token={{ token.content }}"
    
    - name: Make an API call to create the adapter instance
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/adapters{{ auth_token }}"
        method: POST
        body: "{{ adapter_properties }}"
        body_format: json
        headers:
          Content-Type: "application/json"
        status_code: [200,400,500]
        return_content: yes
      register: response
    
    - name: Extract the response of an API call
      set_fact:
        creation_response: "{{ response.content }}"
    
    - name: Start the adapter
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ ansible_host }}:{{ iap_port }}/adapters/{{ creation_response.data.name }}/start{{ auth_token }}"
        method: PUT
        status_code: [200,400,500]
        return_content: yes
      when: creation_response.status is defined and creation_response.status == "Created"
    
    - name: Display the response.
      ansible.builtin.debug: 
        msg:
          - "{{ creation_response }}"

