# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

- hosts: platform
  tasks:

    # Request an IAP session token to use with the following IAG requests.
    # Register the response from this login service to be referenced by later
    # tasks.
    - name: Get IAP token
      ansible.builtin.uri:
        url: "{{ iap_protocol }}://{{ inventory_hostname }}:{{ iap_port }}/login"
        method: POST
        body_format: json
        follow_redirects: true
        body:
          user:
            username: "{{ iap_username }}"
            password: "{{ iap_password }}"
      register: token_response

    - name: Display token
      ansible.builtin.debug:
        msg: "{{ token_response.cookies.token }}"