# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# This playbook retrieves RBAC (Role-Based Access Control) settings for one or more users.
# It gathers authorization accounts and roles from the Itential Platform API, then processes
# the data to display the RBAC settings for the specified users.

# The 'users' variable can be provided as:
# - A single username (string)
# - A list of usernames (list)

# Example usage:
# Pass a single user:
# ansible-playbook -i hosts rbac_settings.yml -e users=admin

# Pass multiple users:
# ansible-playbook -i hosts rbac_settings.yml -e "users=['admin','alex','sam']

- name: RBAC Settings
  hosts: platform
  gather_facts: false
  connection: local
  tasks:
    - name: Retrieve authorization accounts # noqa syntax-check
      itential.platform.generic_request:
        method: GET
        endpoint: "/authorization/accounts"
      register: auth_accounts

    - name: Retrieve available roles # noqa syntax-check
      itential.platform.generic_request:
        method: GET
        endpoint: "/authorization/roles"
      register: roles_response

    - name: Process RBAC Data
      itential.toolkit.platform_rbac_processing:
        auth_accounts: "{{ auth_accounts.json.results }}"
        roles_response: "{{ roles_response.json.results }}"
        users: "{{ users }}"
      register: rbac_results

    - name: Display the RBAC Settings for users
      ansible.builtin.debug:
        msg: "{{ rbac_results.formatted_message.split('\n') }}"
