# Copyright (c) 2024, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# This playbook updates the Redis `itential` user's password,
# updates the Platform properties file with the new password,
# and restarts redis and platform to apply the change.

# To hide sensitive data, use ansible-vault to encrypt passwords.

# Example usage:
# ansible-playbook redis_change_password.yml -i hosts \
#   -e "redis_new_password=newpass"

- name: Update Redis password and restart platform
  hosts: redis,platform
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: Deactivate Platform workers
      when: "'platform' in group_names"
      ansible.builtin.include_role:
        name: restart_platform
        tasks_from: shutdown_workers
      tags: deactivate_workers

    - name: Update Redis password on Redis hosts
      when: "'redis' in group_names"
      block:
        - name: Check that 'itential' user is present in redis.conf
          ansible.builtin.slurp:
            path: /etc/redis/redis.conf
          register: redis_conf_content
          no_log: true

        - name: Fail if 'itential' user not found in redis.conf
          ansible.builtin.fail:
            msg: "'itential' user not found in redis.conf"
          when: redis_conf_content['content'] | b64decode | regex_search('^user itential .*?>.*$', multiline=True) is none
          no_log: true

        - name: Update redis.conf with new password for 'itential' user
          ansible.builtin.replace:
            path: /etc/redis/redis.conf
            regexp: '^user itential (.*) >.*$'
            replace: 'user itential \1 >{{ redis_new_password }}'
          no_log: true

        - name: Restart Redis service
          ansible.builtin.systemd:
            name: redis
            state: restarted


    - name: Update and restart platform
      when: "'platform' in group_names"
      block:
        - name: Update platform.properties with new Redis password
          ansible.builtin.replace:
            path: /etc/itential/platform.properties
            regexp: '^redis_password\s*=.*$'
            replace: "redis_password = {{ redis_new_password }}"
          no_log: true

        - name: Restart Platform
          ansible.builtin.include_role:
            name: restart_platform
            tasks_from: restart
