# Copyright (c) 2022, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# This playbook restarts one or more adapters on the Itential Platform using the Platform API.
# It accepts adapter names via the 'adapters' variable and invokes the restart action for each.

# The 'adapters' variable can be provided as:
# - A single adapter name (string)
# - A list of adapter names (list)

# Example usage:
# Restart a single adapter:
# ansible-playbook -i hosts restart_adapters.yml -e adapters=netbox

# Restart multiple adapters:
# ansible-playbook -i hosts restart_adapters.yml -e "adapters=['netbox','servicenow','infoblox']"

- name: Restart Adapters
  hosts: platform
  gather_facts: false
  roles:
    - auth_token
  tasks:
    - name: Restart specified adapters
      itential.platform.restart_adapters:
        adapter_names: "{{ adapters }}"
