# Copyright (c) 2024, Itential, LLC
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# This playbook updates the Redis Sentinel `sentineluser` password,
# updates the Platform properties file with the new password,
# and restarts redis, sentinel, and platform to apply the change.

# To hide sensitive data, use ansible-vault to encrypt passwords.

# Example usage:
# ansible-playbook redis_sentinel_change_password.yml -i hosts \
#   -e "sentinel_new_password=newpass"

- name: Update Platform Configuration
  hosts: platform*
  gather_facts: false
  any_errors_fatal: true
  roles:
    - itential.toolkit.restart_platform
  tasks:
    - name: Update platform.properties with new Redis Sentinel password
      ansible.builtin.replace:
        path: /etc/itential/platform.properties
        regexp: '^redis_sentinel_password\s*=.*$'
        replace: "redis_sentinel_password = {{ sentinel_new_password }}"
      no_log: true
      notify: Restart platform

- name: Update password in Redis and Sentinel Configurations
  hosts: redis*
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Check that 'sentineluser' user is present in redis.conf
      ansible.builtin.slurp:
        path: /etc/redis/redis.conf
      register: redis_sentinel_conf_content

    - name: Fail if 'sentineluser' user not found in redis.conf
      ansible.builtin.fail:
        msg: "'sentineluser' user not found in redis.conf"
      when: >
        redis_sentinel_conf_content['content'] | b64decode |
        regex_search('^user sentineluser .*?>.*$', multiline=True) is none

    - name: Hash sentinel password with SHA-256
      ansible.builtin.set_fact:
        sentinel_password_sha256: "{{ sentinel_new_password | hash('sha256') }}"

    - name: Update Sentinel configuration with new password
      notify: Restart Sentinel
      block:
        - name: Update hashed password for sentineluser in sentinel.conf
          ansible.builtin.lineinfile:
            path: /etc/redis/sentinel.conf
            regexp: '^(user sentineluser on sanitize-payload ).*?( \&.+$)'
            line: '\1#{{ sentinel_password_sha256 }}\2'
            backrefs: true

        - name: Update sentinel auth-pass for master in sentinel.conf
          ansible.builtin.replace:
            path: /etc/redis/sentinel.conf
            regexp: '^sentinel auth-pass itentialmaster .*'
            replace: 'sentinel auth-pass itentialmaster {{ sentinel_new_password }}'
          no_log: true

        - name: Update sentinel sentinel-pass in sentinel.conf
          ansible.builtin.replace:
            path: /etc/redis/sentinel.conf
            regexp: '^sentinel sentinel-pass .*'
            replace: 'sentinel sentinel-pass {{ sentinel_new_password }}'
          no_log: true

    - name: Update password for sentineluser in redis.conf
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^(user sentineluser .*?>).*?$'
        line: '\1{{ sentinel_new_password }}'
        backrefs: true
      notify: Restart Redis
      no_log: true

  handlers:
    - name: Restart Redis
      ansible.builtin.systemd:
        name: redis
        state: restarted

    - name: Restart Sentinel
      ansible.builtin.systemd:
        name: redis-sentinel
        state: restarted
