name: Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-ansible ansible ansible-core requests urllib3

    - name: Set Ansible Collections Path
      run: |
        echo "ANSIBLE_COLLECTIONS_PATHS=~/.ansible/collections" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest tests/ -v
